{{
    config(
        materialized='view'
    )
}}

SELECT
PRODUCT_ID,
INITCAP(PRODUCT_NAME) AS PRODUCT_NAME,
CATEGORY_ID,
PRICE :: FLOAT AS PRICE,
STOCK_QUANTITY :: INT AS STOCK_QUANTITY,
LOAD_TIMESTAMP
FROM 
{{ ref('LL_PRODUCTS') }}
