{{
    config(
        materialized='table'
    )
}}

SELECT
O.STATE,
C.CATEGORY_NAME,
SUM(OI.QUANTITY) AS UNIT_SOLD,
SUM(OI.QUANTITY * P.PRICE) AS REVENUE
FROM
{{ ref('STG_ORDERS') }} O 
LEFT JOIN {{ ref('STG_ORDER_ITEMS') }} OI 
ON O.ORDER_ID = OI.ORDER_ID
LEFT JOIN {{ ref('STG_PRODUCTS') }} P
ON P.PRODUCT_ID = OI.PRODUCT_ID
LEFT JOIN {{ ref('STG_CATEGORY') }} C 
ON P.CATEGORY_ID = C.CATEGORY_ID
GROUP BY 
O.STATE,
C.CATEGORY_NAME
ORDER BY O.STATE